apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "helm-operator.selectorLabels" . | nindent 4 }}
---
{{- if .Values.webUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-operator.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web-ui
    port: {{ .Values.webUI.port }}
    targetPort: web-ui
    protocol: TCP
  selector:
    {{- include "helm-operator.selectorLabels" . | nindent 4 }}
{{- end }}
